---
- name: Cloning kiterunner repo
  git:
    repo: "https://github.com/assetnote/kiterunner"
    dest: "/tmp/kiterunner"

- name: "building kiteunner"
  shell: |
    cd /tmp/kiterunner
    make build

- name: Moving kr to bin
  copy:
    src: "/tmp/kiterunner/dist/kr"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'


- name: Cloning the kerbrute repo
  git:
    repo: "https://github.com/ropnop/kerbrute"
    dest: "/tmp/kerbrute"

- name: Building kerbrute
  shell: |
    cd /tmp/kerbrute
    go build

- name: Moving kerbrute to bin
  copy:
    src: "/tmp/kerbrute/kerbrute"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'


- name: Cloning ffuf repo
  git:
    repo: "https://github.com/ffuf/ffuf"
    dest: "/tmp/ffuf"

- name: Building ffuf
  shell: |
    cd /tmp/ffuf
    go get
    go build

- name: Moving ffuf to bin
  copy:
    src: "/tmp/ffuf/ffuf"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'

- name: Downloading kubeletctl
  ansible.builtin.get_url:
    url: "https://github.com/cyberark/kubeletctl/releases/latest/download/kubeletctl_linux_amd64"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubeletctl"
    mode: '750'
    timeout: 30
  async: 40
  poll: 0