---
- name: Cloning kiterunner repo
  git:
    repo: "https://github.com/assetnote/kiterunner"
    dest: "/tmp/kiterunner"

- name: "building kiteunner"
  shell: |
    cd /tmp/kiterunner
    make build

- name: Moving kr to bin
  copy:
    src: "/tmp/kiterunner/dist/kr"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'

- name: Cloning the kerbrute repo
  git:
    repo: "https://github.com/ropnop/kerbrute"
    dest: "/tmp/kerbrute"

- name: Building kerbrute
  shell: |
    cd /tmp/kerbrute
    go build

- name: Moving kerbrute to bin
  copy:
    src: "/tmp/kerbrute/kerbrute"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'

- name: Getting latest release of ffuf
  uri:
    url: "https://api.github.com/repos/ffuf/ffuf/releases/latest"
  register: ffuf_release

- name: Download ffuf
  ansible.builtin.get_url:
    url: "https://github.com/ffuf/ffuf/releases/latest/download/ffuf_{{ ffuf_release.json.tag_name | regex_search('(?<=v)[0-9]+\\.[0-9]+\\.[0-9]+') }}_linux_amd64.tar.gz"
    dest: "/tmp/ffuf.tar.gz"
    timeout: 30

- name: Extracting ffuf
  ansible.builtin.unarchive:
    src: "/tmp/ffuf.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'    

- name: Downloading latest version of feroxbuster
  ansible.builtin.get_url:
    url: "https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.tar.gz"
    dest: "/tmp/feroxbuster.tar.gz"
    timeout: 30

- name: Extracting feroxbuster
  ansible.builtin.unarchive:
    src: "/tmp/feroxbuster.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: '0750'

- name: Downloading kubeletctl
  ansible.builtin.get_url:
    url: "https://github.com/cyberark/kubeletctl/releases/latest/download/kubeletctl_linux_amd64"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubeletctl"
    mode: '0750'
    timeout: 30
  async: 40
  poll: 0
  