---
- name: "installing pipx"
  ansible.builtin.pip:
    name:
      - pipx

- name: "ensuring pipx path"
  shell: pipx ensurepath

- name: "installing tools via pipx"
  community.general.pipx:
    name: "{{ item.name }}"
  loop:
    - { name: "arjun" }
    - { name: "bloodhound" }
    - { name: "certipy-ad" }
    - { name: "git-dumper" }
    - { name: "crackmapexec" }
