---
- name: Installing pipx
  ansible.builtin.pip:
    name:
      - pipx
      - pwntools

- name: Ensuring pipx path
  shell: pipx ensurepath

- name: Installing tools via pipx
  community.general.pipx:
    name: "{{ item.name }}"
    state: latest
  loop:
    - { name: "arjun" }
    - { name: "certipy-ad" }
    - { name: "git-dumper" }
    - { name: "bloodhound" }
    - { name: "crackmapexec" }
