---
- name: Installing pipx
  ansible.builtin.pip:
    name:
      - pipx
      - pwntools

- name: Ensuring pipx path
  shell: pipx ensurepath

- name: Installing tools via pipx
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: "arjun", url: "git+https://github.com/s0md3v/Arjun.git" }
    - { name: "bloodhound", url: "git+https://github.com/dirkjanm/BloodHound.py.git" }
    - { name: "certipy-ad", url: "git+https://github.com/ly4k/Certipy.git" }
    - { name: "git-dumper", url: "git+https://github.com/arthaud/git-dumper" }
    - { name: "crackmapexec", url: "git+https://github.com/mpgn/CrackMapExec.git" }
