---
- name: "installing softwares from apt"
  package:
    name:
      # - golang
      # - docker.io
      - jq
      - ntpdate
      - flameshot
      - exiftool
    state: present
  become: true
  become_method: sudo

- name: "installing docker-compose"
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0711'
  become: true
  become_method: sudo
  async: 120
  poll: 0
