---
- name: Installing softwares from repo
  package:
    name:
      - jq
      - ntpdate
      - exiftool
      # - docker.io
      - flameshot
      - apt-transport-https
    state: present
  become: true
  become_method: sudo

- name: Downloading some other stuffs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: '755'
    timeout: 30
  loop:
    - { url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64", name: "docker-compose" }
    - { url: "https://dl.k8s.io/release/{{ lookup('url','https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl", name: "kubectl" }
  become: true
  become_method: sudo
  async: 80
  poll: 0
