---
- name: Installing tools from repo
  apt:
    name: "{{ item }}"
    state: present
  become: true
  become_method: sudo
  loop:
    - jq
    - ghidra
    - ntpdate
    - mingw-w64
    - exiftool
    - docker.io
    - flameshot
    - burpsuite
    - apt-transport-https
  ignore_errors: true

- name: Downloading some other stuffs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: '0711'
    timeout: 30
  loop:
    - { url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64", name: "docker-compose" }
    - { url: "https://dl.k8s.io/release/{{ lookup('url','https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl", name: "kubectl" }
  become: true
  become_method: sudo
  async: 80
  poll: 0
