---
- name: "Customizing Parrot VM"
  hosts: virtualmachines
  connection: local
  roles:
    - role: "roles/initialize"
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/install-tools"
