---
- name: Getting bashrc and bash_profile path
  stat:
    path: "{{ item }}"
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.bash_profile"
  register: file_stat

- name: Backing up bashrc and bash_profile
  copy:
    src: "{{ ansible_env.HOME }}/{{ item.name }}"
    dest: "{{ ansible_env.HOME }}/{{ item.name }}.bak"
  loop:
    - { status: "{{ file_stat.results[0] }}", name: ".bashrc" }
    - { status: "{{ file_stat.results[1] }}", name: ".bash_profile" }
  when: item.status.stat.exists
  no_log: true

- name: Copying bashrc and bash_profile to HOME
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}"
  loop:
    - ".bashrc"
    - ".bash_profile"

- name: Changing default profile -> Dragon
  shell:
    cmd: "dconf load /org/mate/terminal/profiles/default/ < {{ role_path }}/files/dconf-dump-dragon"
  when:
    - ansible_distribution == 'Parrot'
    - ansible_env.XDG_CURRENT_DESKTOP == 'MATE'
