---
- name: "copy bashrc file"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"

- name: "changing default profile -> Dragon"
  shell:
    cmd: "dconf load /org/mate/terminal/profiles/default/ < {{ role_path }}/files/dconf-dump-dragon"
