---
- name: Copy myip.sh script to /opt
  copy:
    src: "{{ role_path }}/files/myip.sh"
    dest: /opt
    mode: '0755'
  become: true
  become_method: sudo

- name: Create target.txt file in /opt
  file:
    path: /opt/target.txt
    state: touch
  become: true
  become_method: sudo

- name: Change target.txt ownership to user
  file:
    path: /opt/target.txt
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  become_method: sudo