---
 - name: Installing tmux
   ansible.builtin.apt:
     name: tmux
     state: present
   become: true
   become_method: sudo

 - name: Copy tmux config
   copy:
     src: "{{ role_path }}/files/.tmux.conf"
     dest: "{{ ansible_env.HOME }}"

 - name: Copying setup scripts to path
   copy:
     src: "{{ role_path }}/files/{{ item }}"
     dest: "{{ ansible_env.HOME }}/.local/bin/"
     mode: '0740'
   loop:
     - "make-setup"
     - "set-target"

