---
- name: Cleanup using apt
  apt:
    name: "{{ item }}"
    autoremove: yes
    state: absent
  become: true
  become_method: sudo
  ignore_errors: true
  loop:
    - "codium"
    - "impacket-scripts"