---
- name: Install AuditD
  apt:
    name: auditd
    state: present
  become: true
  become_method: sudo

- name: Configure Audit Rules
  copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    mode: 0640
  become: true
  become_method: sudo

