---
# - name: Enable rsyslog service
#   service:
#     name: rsyslog
#     state: started
#     enabled: yes
#   become: true
#   become_method: sudo

- name: Configuring UFW
  ufw:
    state: enabled
  become: true
  become_method: sudo

# - name: Log SYN packets in INPUT chain
#   lineinfile:
#     path: /etc/ufw/after.rules
#     line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
#     insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
#   become: true
#   become_method: sudo
