---
- name: Check if certificate exists
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: cert

- name: Copying getburpcert script
  copy:
    src: "{{ role_path }}/files/getburpcert.sh"
    dest: /tmp/getburpcert.sh
    mode: '0744'
  when: cert.stat.exists == false

- name: Executing script to download Burp CA cert
  shell: /tmp/getburpcert.sh
  when: cert.stat.exists == false

- name: Copying certificate to path
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
  become: true
  become_method: sudo
  when: cert.stat.exists == false

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    mode: '644'
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"
  become: true
  become_method: sudo

- name: Copy BurpSuite Community Config
  template:
    src: "{{ role_path }}/templates/UserConfigCommunity.json.j2"
    dest: "{{ ansible_env.HOME }}/.BurpSuite/UserConfigCommunity.json"
