---
- name: Download Sublime Text GPG key
  get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /tmp/sublimehq-pub.gpg

- name: Add Sublime Text GPG key to trusted directory
  shell: gpg --dearmor /tmp/sublimehq-pub.gpg | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null

- name: Add Sublime Text repository to sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/sublime-text.list
    line: "deb https://download.sublimetext.com/ apt/stable/"
    create: yes
  become: true
  become_method: sudo
